# Application Configuration
spring.application.name=simple-java-app
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example=simple_java_app=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Metrics
management.metrics.export.prometheus.enabled=true
